In [1]:
import pandas as pd

In [9]:
df_s = pd.read_csv('stocks.csv')

In [19]:
df = pd.read_csv('../stocks_names.csv')

df = pd.merge(df, df_s, on='stock')
df

,stock,weird_num,set,captial,something,name,short_name,Unnamed: 0,mean_mid_price,mean_spread,...,test_mid_price_indicator_ratio,test_set_length,train_dates,train_length,train_set_length,diff_mean_mid_price,diff_mid_price_indicator_ratio,diff_mean_spread,km,is_choosen
0,9061,GB0005405286,SET0,GB,GBX,HSBC Holdings,HSB,87,686.151230,0.167577,...,0.763242,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,5.482594,0.000271,0.036031,0,1
1,3459,GB00B08SNH34,SET1,GB,GBX,National Grid plc,NGG,19,752.117731,0.646266,...,0.244043,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,26.762586,0.000841,0.017260,0,1
2,2822,GB0033277061,SET1,GB,GBX,Vedanta Resources plc,VED,52,1102.788002,1.901099,...,0.257484,4958,"('2013-09-02 08:30:00', '2013-11-01 08:30:00')",19828,19828,55.273782,0.017071,0.034621,2,0
3,9761,GB0000595859,SET1,GB,GBX,ARM Holdings plc,ARM,33,973.908411,0.939125,...,0.417548,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,18.529354,0.004248,0.137875,0,1
4,4851,GB00B39J2M42,SET1,GB,GBX,United Utilities,UU,78,696.995186,0.769056,...,0.166706,4963,"('2013-09-02 08:30:00', '2013-10-31 15:57:00')",19836,19836,6.951764,0.005704,0.042681,0,1
5,9062,GB0007188757,SET0,GB,GBX,Rio Tinto,RIO,28,3120.336399,0.966438,...,0.818182,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,145.943535,0.004122,0.048982,1,1
6,3879,GB00B10RZP78,SET1,GB,GBX,Unilever,ULVR,3,2456.725912,1.200665,...,0.428571,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,28.525650,0.028839,0.024693,1,0
7,1431,GB0002405495,SET1,GB,GBX,Schroders PLC,SDR,69,2553.911820,2.329788,...,0.395892,4962,"('2013-09-02 08:30:00', '2013-10-31 15:57:00')",19840,19840,22.472884,0.017923,0.022489,1,0
8,2748,GB0032089863,SET1,GB,GBX,Next,NXT,21,5128.616356,5.644103,...,0.159691,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19840,19840,367.098218,0.007505,0.919090,1,1
9,4320,GB00B1KJJ408,SET1,GB,GBX,Whitbread,WTB,82,3150.772656,1.890978,...,0.439895,4960,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19840,19840,277.515953,0.009761,0.187450,1,1
10,11583,GB0002374006,SET0,GB,GBX,Diageo,DGE,39,1984.517965,0.780740,...,0.562697,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,11.817048,0.000069,0.051653,2,1
11,4799,GB00B2QPKJ12,SET1,GB,GBX,Fresnillo,FRES,64,1041.757428,1.743972,...,0.376353,4960,"('2013-09-02 08:30:00', '2013-10-31 15:55:00')",19824,19824,84.137468,0.000451,0.069778,2,1
12,2730,GB0031809436,SET1,GB,GBX,Land Securities Group plc,LAND,76,934.176676,0.776235,...,0.321876,4962,"('2013-09-02 08:30:00', '2013-10-31 15:59:00')",19840,19840,39.928574,0.015753,0.011322,0,0
13,10470,GB0009465807,SET1,GB,GBX,Weir Group,WEIR,55,2314.327218,1.805948,...,0.337106,4963,"('2013-09-02 08:30:00', '2013-10-31 15:56:00')",19840,19840,119.043518,0.003072,0.170243,2,1
14,9058,GB0000566504,SET0,GB,GBX,BHP Billiton Plc,BLT,72,1877.535943,0.743928,...,0.662198,4961,"('2013-09-02 08:30:00', '2013-10-31 16:00:00')",19844,19844,68.535515,0.004244,0.093454,2,1

In [20]:
df.columns

Index(['stock', 'weird_num', 'set', 'captial', 'something', 'name',
       'short_name', 'Unnamed: 0', 'mean_mid_price', 'mean_spread',
       'mid_price_indicator_ratio', 'test_dates', 'test_length',
       'test_mean_mid_price', 'test_mean_spread',
       'test_mid_price_indicator_ratio', 'test_set_length', 'train_dates',
       'train_length', 'train_set_length', 'diff_mean_mid_price',
       'diff_mid_price_indicator_ratio', 'diff_mean_spread', 'km',
       'is_choosen'],
      dtype='object')

In [24]:
print(df.sort_values(by='km')[['stock', 'short_name', 'mean_spread', 'mean_mid_price']].to_latex())

\begin{tabular}{lrlrr}
\toprule
{} &  stock & short\_name &  mean\_spread &  mean\_mid\_price \\
\midrule
0  &   9061 &        HSB &     0.167577 &      686.151230 \\
1  &   3459 &        NGG &     0.646266 &      752.117731 \\
3  &   9761 &        ARM &     0.939125 &      973.908411 \\
4  &   4851 &         UU &     0.769056 &      696.995186 \\
12 &   2730 &       LAND &     0.776235 &      934.176676 \\
5  &   9062 &        RIO &     0.966438 &     3120.336399 \\
6  &   3879 &       ULVR &     1.200665 &     2456.725912 \\
7  &   1431 &        SDR &     2.329788 &     2553.911820 \\
8  &   2748 &        NXT &     5.644103 &     5128.616356 \\
9  &   4320 &        WTB &     1.890978 &     3150.772656 \\
2  &   2822 &        VED &     1.901099 &     1102.788002 \\
10 &  11583 &        DGE &     0.780740 &     1984.517965 \\
11 &   4799 &       FRES &     1.743972 &     1041.757428 \\
13 &  10470 &       WEIR &     1.805948 &     2314.327218 \\
14 &   9058 &        BLT &     0.743928 &     1877.535943 \\
\bottomrule
\end{tabular}